### ISSUE TITLE
Unable to log into Cormyr server

### ISSUE THREAD

**Issue by Purpletimb** [traversc/DDO-ML#10]
I've not been able to get DDO-ML to log into the new Cormyr server.  ddolauncher.exe returns error:  "World queue returned an error."

**Comment by MIvanIsten** [comment]
Just checked, and had no problem.
If you still can't login, try again few times (login queue can be busy).
If no success after few retries:
- exit DDO-ML
- set `debug=2` in `ddo-ml.ini`
- delete `ddolauncher.txt` if exists
- restart DDO-ML and try login
- after fail exit DDO-ML
- make sure to *** out your login and password in `ddolauncher.txt`, then post its contents here
