### ISSUE TITLE
"Trojan:Win32/Bitrep.A" detected in preload.exe

### ISSUE THREAD

**Issue by Git0utOfHere** [traversc/DDO-ML#5]
Windows Defender picked up the following.

Trojan:Win32/Bitrep.A
File:DDO-ML-master\preload.exe
Date:March 1st, 2018

**Comment by traversc** [comment]
I believe that is likely a false positive; @MIvanIsten added the C++ program and you can check the source and/or compile it to be sure.  

Compiling is pretty straightforward and easy: https://stackoverflow.com/questions/11365850/run-c-in-command-prompt-windows
