### ISSUE TITLE
The requested action with this object has failed

### ISSUE THREAD

**Issue by drixtol** [traversc/DDO-ML#7]
Line 9010 (file "d:\ddolauncher\ddo-ml-master\ddolauncher.exe"):

Error: The requested action with this object has failed.

-----
App fails for to work when any server is offline, even if its not the selected server. 

![image](https://user-images.githubusercontent.com/20601906/89338740-e02d9480-d651-11ea-98ea-00fc1c87dc07.png)

**Comment by traversc** [comment]
@MIvanIsten
