### ISSUE TITLE
Error 500: Internal Server Error

### ISSUE THREAD

**Issue by iplaywithdrums** [traversc/DDO-ML#8]
Hello. I am getting the error of "HTTP post failed. Error 500: Internal Server Error."

I have gotten successful client launches before but now it won't stop giving me this error. How do I fix this?

**Comment by MIvanIsten** [comment]
I need a little bit more info on whats happening, so:
- Stop DDO-ML
- Update you ddo-ml.ini to have debug=2 in it
- If you have debug.txt or ddolauncher.txt in your DDO-ML folder, delete them
- Start DDO-ML, select a character to load, wait for error to happen, stop DDO-ML
- After ***-ing out all instances of your user name and password, post the contents of debug.txt and ddolauncher.txt

**Comment by iplaywithdrums** [comment]
Okay, looking at debug.txt, I was able to debug it myself. Somehow, when I was encrypting before, the password value got transformed into "836F16707BA944040B4273AABD849C09" which reads as "ÿÿÿÿ". Odd.

Thanks!
